const classesList = [
  {
    topic: "Arts",
    startDateText: "May 10th",
    startDateValue: 5.1,
    endDateText: "June 10th",
    endDateValue: 6.1,
    classChosen: false,
    uuid: "arts_1",
  },
  {
    topic: "Arts",
    startDateText: "July 11th",
    startDateValue: 7.11,
    endDateText: "August 11th",
    endDateValue: 8.11,
    classChosen: false,
    uuid: "arts_2",
  },
  {
    topic: "Literature",
    startDateText: "July 11th",
    startDateValue: 7.11,
    endDateText: "October 11th",
    endDateValue: 10.11,
    classChosen: false,
    uuid: "literature_1",
  },
  {
    topic: "Music",
    startDateText: "June 9th",
    startDateValue: 6.09,
    endDateText: "July 9th",
    endDateValue: 5.1,
    classChosen: false,
    uuid: "music_1",
  },
  {
    topic: "Music",
    startDateText: "August 9th",
    startDateValue: 8.09,
    endDateText: "September 9th",
    endDateValue: 9.09,
    classChosen: false,
    uuid: "music_2",
  },
  {
    topic: "Sports",
    startDateText: "July 23rd",
    startDateValue: 7.23,
    endDateText: "August 23rd",
    endDateValue: 8.23,
    classChosen: false,
    uuid: "sports_1",
  },
  {
    topic: "Sports",
    startDateText: "August 26th",
    startDateValue: 8.26,
    endDateText: "September 26th",
    endDateValue: 9.26,
    classChosen: false,
    uuid: "sports_2",
  },
];
export default classesList;
